version: "3"
services:
  service:
    build:
      context: service
      network: host
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default
    expose:
      - ${UVICORN_PORT}
    volumes:
      - ./service/logs:/opt/link_dst/service/logs/:rw
    
    entrypoint: >
      uvicorn app:app
      --host ${UVICORN_HOST}
      --port ${UVICORN_PORT}
      --workers ${UVICORN_WORKERS}
      --log-level ${UVICORN_LOG_LEVEL}
  admin:
    build:
      context: admin
      network: host
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./admin/static:/var/www/:rw
    expose:
      - "80"
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./admin/static:/var/www/:ro
    ports:
      - "80:80"
    depends_on:
      - service
      - admin
    networks:
      - default

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
      POSTGRES_HOST: ${postgres_host}
      POSTGRES_PORT: ${postgres_port}
    expose:
      - ${postgres_port}
    env_file:
      - .env
    networks:
      - default
      
networks:
  default:
    driver: bridge
      